language: java
jdk:
  - openjdk11

branches:
  only:
    - master

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-hs-webservice *
  - mkdir -p deploy
  - mv springboot-hs-webservice.zip deploy/springboot-hs-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hs-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hs-springboot-build
    key: springboot-hs-webservice.zip
    bundle_type: zip
    application: hs-springboot2-webservice
    deployment_group: hs-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - minvita9999@naver.com

before_install:
  - chmod +x gradlew
